# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jackie Johnston
description: > # this means to ignore newlines until "baseurl:"
  Jackie Johnston's portfolio website, showcasing her art, photography and coding work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jackiejohnston.us" # the base hostname & protocol for your site
author: Jackie Johnston
twitter: 
  username: heartsbeach

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md'
]

# Build settings
markdown: kramdown

gems:
  - jekyll-autoprefixer
  - jekyll-seo-tag

sass:
  style: compressed

# Set Jekyll's env to enable/disable Uglifier    
env: 'production'    

stitch:
  dependencies: 
    - 'js/jquery.min.js'
    - 'js/bootstrap.min.js'
    - 'js/site.js'
    - 'js/prism.min.js'
    - 'js/clipboard.js'
    - 'js/anchor.min.js'
    - 'js/modernizr.custom.js'
    - 'js/masonry.pkgd.min.js'
    - 'js/imagesloaded.js'
    - 'js/classie.js'
    - 'js/AnimOnScroll.js'
    - 'js/photoswipe.js'
    - 'js/photoswipe-ui-default.js'
  output: 'js/main.min.js'
  fingerprint: false
  cleanup: true
  uglify: true
  uglify_options: {}  

collections:
  snippets:
    output: false
